### ISSUE TITLE
رو سرور فیلتر خارج جواب نمیده

### ISSUE THREAD

**Issue by KanekiDevPro** [Ptechgithub/wstunnel#1]
سلام رو رو سرور فیلتر خارج جواب نمیده ؟؟؟ چون کلا رو هر سروری تست میکنم نمیشه

**Comment by Ptechgithub** [comment]
سلام حتما اشتباه نصب کردی

**Comment by KanekiDevPro** [comment]
رو یه سرور غیر فیلتر اوکی بود اخه عجیبهههه

**Comment by Ptechgithub** [comment]
سرور فیلتر باشه که کار نمیکنه از reverse استفاده کن

**Comment by amirakumu** [comment]
میشه کانفیگ روی vless tcp انجام داد ؟
