### ISSUE TITLE
متوقع شدن سرویس بعد از چند دقیقه

### ISSUE THREAD

**Issue by Eslender73** [Ptechgithub/wstunnel#3]
پنل مورد استفاده هیدیفای
پورت تانل ۸۰۸۰
پورت کانفیگ ۸۰
بدون tls 
Vmess tcp http

بعد از چند دقیقه سرویس متوقف میشه و دوباره باید اسکریپتو نصب کنم

**Comment by Ptechgithub** [comment]
احتمالا اختلال از سرور یا پورت باشه . پورت روعوض کن مجدد تست بگیر

**Comment by Eslender73** [comment]
پورتارو همرو متفرقه زدم تغییری نکرد حتی زودتر قعط میشه در حد ۵ دقیقه
یبار سرویسو ریستارت میکنم با این دستور درست میشه
systemctl restart wstunnel
