### ISSUE TITLE
arm64 cpu

### ISSUE THREAD

**Issue by id1nxd** [Ptechgithub/wstunnel#4]
فکر کنم روی arm64 هتزنر جواب نمیده درسته؟
 wstunnel.service - WsTunnel
     Loaded: loaded (/etc/systemd/system/wstunnel.service; enabled; vendor pres>     Active: failed (Result: exit-code) since Tue 2024-01-09 03:32:44 UTC; 7s a>    Process: 72030 ExecStart=/usr/local/bin/wstunnel client -R tcp://[::]:9443:>   Main PID: 72030 (code=exited, status=203/EXEC)
        CPU: 1ms
Jan 09 03:32:44 ubuntu-4gb-hel1-1 systemd[1]: Started WsTunnel.
Jan 09 03:32:44 ubuntu-4gb-hel1-1 systemd[1]: wstunnel.service: Main process ex>Jan 09 03:32:44 ubuntu-4gb-hel1-1 systemd[1]: wstunnel.service: Failed with res>

**Comment by Ptechgithub** [comment]
جواب میده

**Comment by V2RVPNShop** [comment]
منم همین مشکل را داشتم اما با یه تغییر کوچک توی کد درست شد.
