### ISSUE TITLE
سینک دو اسکریپت

### ISSUE THREAD

**Issue by javad48** [Ptechgithub/wstunnel#5]
سلام با این روش میشه دو پنل x-ui رو به هم سینک کرد؟

**Comment by Ptechgithub** [comment]
سلام سینک پنل یعنی چی؟ این فقط برای تانل دو تا سروره

**Comment by javad48** [comment]
> سلام سینک پنل یعنی چی؟ این فقط برای تانل دو تا سروره

سلام و وقت بخیر
من یه پنل دیدم تانله هرچی تغییرات روی خارج بزنی روی پنل ایران هم اعمال میشه.میخوام روشش بدونم
اما فقط میدونم وبسوکت تانل هم هست

**Comment by Ptechgithub** [comment]
خیر همچین چیزی ندیدم
